minimal_mistakes_skin: sunrise
locale: en-US
title: Data Wanderer
title_separator: '-'
subtitle: 'Garbage in, garbage out'
name: 
description: >-
  This is my personal blog with opinions and views on what I read/watch/explore.
  This does not convey or represent views of my employer(s)
url: 'https://sahyagiri.github.io'
baseurl: '/'
repository: 'sahyagiri/sahyagiri.github.io'
teaser: 'assets/teaser1.jpg'
logo: 'assets/icon1.png'
masthead_title: null
words_per_minute: 200
comments:
 # provider: "utterances"
 # utterances:
 #   theme: "github-light" # "github-dark"
 #   issue_term: "pathname"
  provider: 'staticman_v3'   
  staticman:
    branch    : "master"
    endpoint  : https://my-blog-comments.herokuapp.com/v3/entry/github/sahyagiri/sahyagiri/
reCaptcha:
  siteKey: "6LcURsAZAAAAALDlYf3unFONOwwe4hzS97mZSTcO"
  secret: o6PqWhX2UxGfLAsQorT0b/6KrSrgrZJ3C1wlGi2wRDXm66hYbC8cfEdF4LiBEMsZylekc0O17QEvwnSSbYZKkyBE4RvrGmJ528uPJ2wVO31VGxD9t3zNOVZCy3c82+1d8rsjvQGBI3BXkMWBSBR/4MVNuvkH7SqgNRKnOslywVLeTYv8iP2CIAsqzo5J6Yx33LYZnRaP/4kvZOlJJ/zQXb/K5VWpgfxaiC4dqcf0ft+15Hr3IXI1KXE1LUGV93ZSVfa+ishIgYikBExkyy+rc99Sf3KFmC3vMpAfMI9hmDQSHLNK47zbwPXAtCLG4Wcf3xFjt4f77Uf5Aei/P6pJ1Wg86mpiSbbsp3xUgrsBasL/dL0PYTrQgQp40Ts6d1k3KQIp8nCzMIJatfrn73AbErxQ50ta8LinnBg93TNpOJ/ZNTmBVOzaZOkCg8hzrG7A+sWZusi+QY68MXHE5w73/mFH3TTa3/MoPecfNqE9H6O+1EvLffc2PS/jbYtdM7dsGtbWb73Eln5QyumGTcjgfCSJmOizEUuIwJ6m81pKlYm35KRu1oaD4SbDWaGJfJbTrD0ypsaxwCGt9cC5pVjTsiMdYT+sMnmvXyVOK4pzX6ny0bQK3eiLfxXvjaMVaon03xN3tVe25yM3k6tb41woK4nQA01W6poQg79ipA+0c6w=
atom_feed:
  path: null
search: true
search_full_content: null
search_provider: null
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: sahyagiri
facebook:
  username: sahyagiri
  app_id: null
  publisher: null
og_image: 'null'
social:
  type: 'null'
  name: null
  links: null
analytics:
  provider: false
  google:
    tracking_id: null
    anonymize_ip: null
author:
  name: Gireesan Namboothiri P.
  avatar: 'assets/giree.jpg'
  bio: >-
    reading, programming, cooking, cycling, traveling and star gazing
  location: Could be anywhere
  email: sahyagiri@gmail.com
  links:
    - label: Email
      icon: fas fa-fw fa-envelope-square
    - label: Website
      icon: fas fa-fw fa-link
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
    - label: Facebook
      icon: fab fa-fw fa-facebook-square
    - label: GitHub
      icon: fab fa-fw fa-github
    - label: Instagram
      icon: fab fa-fw fa-instagram
footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
    - label: Facebook
      icon: fab fa-fw fa-facebook-square
    - label: GitHub
      icon: fab fa-fw fa-github
    - label: GitLab
      icon: fab fa-fw fa-gitlab
    - label: Bitbucket
      icon: fab fa-fw fa-bitbucket
    - label: Instagram
      icon: fab fa-fw fa-instagram
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
